### ISSUE TITLE
Return in typed if then else

### ISSUE THREAD

**Issue by ioanalex** [ioanalex/cwasm#5]
In this case:

`if (result i32)  block (result i32)
   .... 
  return end
else
   .....
 end`

We get a fatal error generated by the `pop_ctrl()` in `else`. It tries to `pop_opd()` the return type of the `if` instruction (i32) but `return` has already poped it from the operand stack.

`return` is marking the `block` frame as **unreachable** so it can `pop_ctrl()` when ending. The outer frame ( `if ` ) is not marked unreachable though and `pop_ctrl()` fails. Perhaps we need to mark it as well ? 

When debugging set the PRINT_STACKS (*in file util.hpp*) macro to 1 (is it by default).

Reproduce this error by running the *args.wasm* file.

**Comment by nickie** [comment]
This is probably OK, the test file `args.wasm` is not valid.
It contained something like:

`if (result i32) block (no result) .... return end else ..... end`
